services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: twitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    # this option mounts the local folder ./pg-data to the container folder /var/lib/postgresql/data
    # which makes the data persistent even if the container is deleted
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # adminer is a web interface for sql databases
  # visit http://localhost:8081 to access it, login with the credentials above
  # you can see the data in the database and run sql queries
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
